name: Run gulp tasks

on:
  push:
    branches: [ master ]
    paths: ["scripts/custom.js", "styles/*.scss"]
    
jobs:
  build:
  
       runs-on: ${{ matrix.os }}
       
       strategy:
         matrix:
           node-version: [12.x, 14.x]
           os: [macos-latest, windows-latest, ubuntu-latest]

       steps:
       - uses: actions/checkout@v2
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
          node-version: ${{ matrix.node-version }}
          
       -  name: Build
          run: |
            npm i
            gulp
        - run: gulp
